In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_boston

In [2]:
data = load_boston()
print(data.data)

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]


In [3]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(data.data,data.target,test_size = 0.3,random_state=3)
model = LinearRegression().fit(x_train,y_train)
y_pred = model.predict(x_test)
print(y_test)

[44.8 17.1 17.8 33.1 21.9 21.  18.4 10.4 23.1 20.  15.7 41.3 33.3 30.7
  8.5  6.3 21.2 16.2 15.6 24.1 23.9 50.  23.2 23.4 12.8 24.6 18.8 16.1
 18.2 24.3 14.8 37.3 21.4 18.6 18.8 13.9 24.5 31.5 18.2 20.7 19.4  9.7
 21.5 14.9 21.7 26.5 20.7 19.3 24.5 19.3 26.6 23.  45.4 19.8 22.7 23.1
 50.  17.8 29.1 19.2 22.7 21.2 37.2 31.6 16.1 22.2 34.9 20.5 28.  29.1
 24.7 22.  15.6 37.  11.8 21.7 19.4 23.3 16.5 16.7 23.9 15.2 11.9 19.9
 22.8 11.3 25.2 11.5 22.  21.6 19.9 16.8 19.3 50.  29.4 13.3 50.  11.7
 21.7 33.4 20.2 19.4 14.9 19.6 35.4 12.  20.4 23.7 21.  50.  27.5 12.7
 17.4 23.8 22.9 18.5 30.3 31.2 16.  23.3 15.  10.2 12.5 19.6 19.7 19.5
 15.  35.4 13.5 20.6 24.7 21.9 17.1 23.6 21.1 15.6 18.5  8.3 14.5 23.9
 11.8 24.6 24.8 18.7 17.9 48.8 13.  29.6 18.  20.1 17.3 23.1]


In [4]:
from sklearn.metrics import accuracy_score
model.score(x_test,y_test)

0.7147895265576846