In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import confusion_matrix 

In [15]:
data = pd.read_csv("smsdata.txt", sep='\t', names=['label', 'message'])

In [16]:
data.head()

label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

**convert our labels to binary variables**, 0 to represent 'ham'(i.e. not spam) and 1 to represent 'spam' 

In [17]:
data['label'] = data.label.map({'ham':0, 'spam':1})
data.head()

label                                            message
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data['message'], data['label'], test_size =0.2, random_state=99)

In [19]:
from sklearn.feature_extraction.text import CountVectorizer
count_vector = CountVectorizer()

In [20]:
training_data = count_vector.fit_transform(X_train).toarray()
testing_data = count_vector.transform(X_test).toarray()

In [23]:
frequency_matrix = pd.DataFrame(training_data, columns = count_vector.get_feature_names())
frequency_matrix.head()

00  000  000pes  008704050406  0089  0121  01223585236  01223585334  \
0   0    0       0             0     0     0            0            0   
1   0    0       0             0     0     0            0            0   
2   0    0       0             0     0     0            0            0   
3   0    0       0             0     0     0            0            0   
4   0    0       0             0     0     0            0            0   

   0125698789  02  ...  zeros  zhong  zindgi  zoe  zogtorius  zoom  zouk  \
0           0   0  ...      0      0       0    0          0     0     0   
1           0   0  ...      0      0       0    0          0     0     0   
2           0   0  ...      0      0       0    0          0     0     0   
3           0   0  ...      0      0       0    0          0     0     0   
4           0   0  ...      0      0       0    0          0     0     0   

   zyada  èn  〨ud  
0      0   0    0  
1      0   0    0  
2      0   0    0  
3      0   0    0  
4      0   0    0  

[5 rows x 7737 columns]

In [24]:
testing_data

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [25]:
clf = LogisticRegression(random_state=0).fit(training_data, y_train)

In [26]:
predictions = clf.predict(testing_data)

In [27]:
predictions

array([0, 0, 0, ..., 0, 0, 0])

In [28]:
print('Accuracy score: ', format(accuracy_score(y_test, predictions)))
print('Precision score: ', format(precision_score(y_test, predictions)))
print('F1 score: ', format(f1_score(y_test, predictions)))
print('\nConfusion Matrix :\n', confusion_matrix(y_test, predictions)) 

Accuracy score:  0.9820627802690582
Precision score:  0.9714285714285714
F1 score:  0.9315068493150684

Confusion Matrix :
 [[959   4]
 [ 16 136]]
